project:
  type: website
website:
  title: "Image ML Pod Documentation"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home
      - href: docs/documentation.qmd
        text: Documentation
      - href: reference/index.qmd
        text: API Reference
  sidebar:
    contents: auto
    search: true
  bread-crumbs: true

quartodoc:
  style: pkgdown
  dir: reference
  package: image_ml_pod
  title: "API Reference"
    

  
format:
  html:
    theme: cosmo
    toc: true